sudo: false
language: python
python: 2.7
addons:
  apt:
    sources: ['llvm-toolchain-trusty-6.0', 'ubuntu-toolchain-r-test']
    packages:
      - llvm-6.0
      - llvm-6.0-dev
      - g++-5
env:
  global: CXX=g++-5 LLVM_CONFIG=llvm-config-6.0
  matrix:
    - MIASM_TEST_TAG=regression
    - MIASM_TEST_TAG=example
    - MIASM_TEST_TAG=long
    - MIASM_TEST_TAG=llvm
    - MIASM_TEST_TAG=gcc
    - MIASM_TEST_TAG=z3
    - MIASM_TEST_TAG=qemu
    - MIASM_TEST_TAG=cparser
before_script:
- pip install -r optional_requirements.txt
# codespell
- "pip install codespell && git ls-files | xargs codespell --ignore-words=.codespell_ignore 2>/dev/null"
# turn deprecation warning into RuntimeError
- "find . -name '*.py' | xargs sed -i 's/warnings\\.warn(/raise RuntimeError(/g'"
# install
- python setup.py build build_ext
- python setup.py install
script: cd test && python test_all.py -o=$MIASM_TEST_TAG && git ls-files -o --exclude-standard
